/**
 * DAWLabs NestJS ESLint Configuration - TypeScript-Optimized Linting for NestJS Applications
 *
 * @context Specialized ESLint configuration for NestJS applications within the DAWLabs monorepo
 * @purpose Provides TypeScript linting rules optimized for NestJS patterns, dependency injection, decorators, and testing conventions
 * @integration Extended by NestJS applications and plugins that require relaxed TypeScript rules for framework-specific patterns
 * @workflow Extends base TypeScript configuration with NestJS-specific rule overrides and test file accommodations
 *
 * NestJS-Specific Optimizations:
 * - Dependency Injection: Relaxed unused variable rules for constructor-injected dependencies
 * - Decorators: Lenient length and type rules for decorator-heavy NestJS code
 * - Testing: Comprehensive rule relaxations for test files with Jest and testing utilities
 * - Framework Patterns: Allow NestJS-specific patterns that might violate strict TypeScript rules
 *
 * Rule Categories:
 * - TypeScript: Relaxed explicit typing requirements for rapid NestJS development
 * - Console: Enabled for NestJS logging and framework output
 * - Testing: Comprehensive relaxations for e2e and unit test patterns
 * - Code Style: Lenient line length and spacing for complex NestJS imports
 *
 * Integration Patterns:
 * - Templates: Applied to NestJS application templates generated by create-dawlabs-package
 * - Plugins: Extended by NestJS plugin packages for framework-specific linting
 * - Testing: Separate test file rules for comprehensive testing flexibility
 * - Development: Warning-level enforcement for development-time flexibility
 *
 * Performance Considerations:
 * - TypeScript project configuration for accurate type-aware linting
 * - Selective file pattern matching to avoid over-processing
 * - Optimized parser configuration for NestJS decorators and metadata
 *
 * @example
 * // Usage in NestJS application package.json
 * "eslintConfig": {
 *   "extends": ["./config/eslint.nestjs.js"]
 * }
 *
 * // Direct CLI usage
 * npx eslint --config ./config/eslint.nestjs.js src/**//*.ts
 */

import tseslint from '@typescript-eslint/eslint-plugin';
import tsparser from '@typescript-eslint/parser';
import typescriptConfig from './eslint.typescript.js';

export default [
  ...typescriptConfig,
  {
    files: ['**/*.ts', '**/*.tsx'],
    languageOptions: {
      parser: tsparser,
      parserOptions: {
        project: './tsconfig.json',
        tsconfigRootDir: import.meta.dirname,
      },
    },
    plugins: {
      '@typescript-eslint': tseslint,
    },
    rules: {
      // NestJS specific rules
      '@typescript-eslint/no-explicit-any': 'warn',
      '@typescript-eslint/no-non-null-assertion': 'off',
      '@typescript-eslint/explicit-function-return-type': 'off',
      '@typescript-eslint/explicit-module-boundary-types': 'off',

      // Fix unused variables rule for NestJS dependency injection - warning level for development flexibility
      '@typescript-eslint/no-unused-vars': [
        'warn',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_',
        },
      ],

      // Allow more flexibility for NestJS patterns
      '@typescript-eslint/no-unsafe-assignment': 'off',
      '@typescript-eslint/no-unsafe-member-access': 'off',
      '@typescript-eslint/no-unsafe-call': 'off',
      '@typescript-eslint/no-unsafe-return': 'off',
      '@typescript-eslint/restrict-template-expressions': 'off',

      // Enable console for NestJS logging
      'no-console': 'off',

      // NestJS decorators might need relaxed rules
      'max-len': 'off', // NestJS can have longer import statements
    },
  },
  {
    files: ['**/*.e2e-spec.ts', '**/*.spec.ts'],
    rules: {
      // Test-specific relaxations
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/no-unsafe-assignment': 'off',
      '@typescript-eslint/no-unsafe-member-access': 'off',
      '@typescript-eslint/no-unsafe-call': 'off',
      '@typescript-eslint/no-unsafe-return': 'off',
      'max-len': 'off',
    },
  },
];
